version: '3.8'  # Specify the version of docker-compose

services:
  nextjs:
    build: .
    ports:
      - "3000:3000"  # Map port 3000 on the host to port 3000 in the container
    volumes:
      - .:/app  # Mount the current directory to /app in the container
      - /app/node_modules  # Prevent overwriting node_modules in the container
    environment:
      - NODE_ENV=development  # Set the environment variable for development